import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { GoogleReCaptchaProvider } from "react-google-recaptcha-v3";
import RecaptchaWrapper from "./components/reCaptcha";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bigdoorlms",
  description: "Generated by Bigdoor Solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        
          <AuthProvider>
            <Header />
            <RecaptchaWrapper>
            <main>{children}</main>
          </RecaptchaWrapper>
            <Footer />
          </AuthProvider>
        
      </body>
    </html>
  );
}
